
DROP TABLE Prix CASCADE ;
DROP TABLE Periode CASCADE;
DROP TABLE Carte CASCADE; 
DROP TABLE ContenuMenu CASCADE;
DROP TABLE Plat CASCADE;
DROP TABLE Menu CASCADE;
DROP TABLE Boisson CASCADE; 
DROP TABLE QuantiteElem CASCADE;
DROP TABLE Element CASCADE;
DROP TABLE Commande CASCADE;
DROP TABLE Restaurant CASCADE;
DROP TYPE Choix CASCADE;

